language: python
# ===== Linux ======
os: linux
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
  - "pypy3"
jobs:
  include:
    # ======= OSX ========
    - name: "Python 3.8.0 on macOS 10.14"
      os: osx
      osx_image: xcode11.3  # Python 3.8.0 running on macOS 10.14.6
      language: shell
      before_install:
        - python3 --version
        - python3 -m pip install --upgrade pip
        - python3 -m pip install -r tests/requirements.txt
      script: python3 -m pytest
      after_success: python3 -m codecov
    #  ====== WINDOWS =========
    - name: "Python 3.8.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell
      before_install:
        - choco install python --version 3.8.3
        - python --version
        - python -m pip install --upgrade pip
        - python -m pip install --upgrade codecov pytest
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r tests/requirements.txt
  - pip install .
script:
  - pytest
after_success:
  - codecov
